### ISSUE TITLE
make categories to allow pre building of list

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#8]
@nutpantz from story #13 

> I don't pack for different trips as I have a list for the bag based on season and activities
> Ie list of swimming gear for a bag, for when I might so swimming
> list of winter clothes to take. In winter. Etc.
> So the trips screen is really a list of bags or packs for me.

Concerning your activities lists, I think you have the right approach, I am planning to allow user to pre create thematic lists corresponding to his usual activities and then when creating a new trip, user will be asked if he plans to do each activity. New trip will then be pre-filled with an item list corresponding to activities he agreed.

**Comment by nutpantz** [comment]
Your idea is quite good. I hope the items from the activities will be added as sub groups(with their own weight totals) not just as General items. Ie Keeping items listed for swimming in a swimming group so that when repacking or reducing weight items can be easily checked off or the entire group can be removed.  There is nothing funnier than packing swimming gear then only removing most of it to find you still have goggles or other gear packed you know you are not going to use.
Not so funny when you realize you paid for the extra issues weight.

Having everything sorted in to groups help me organize each of my luggage bags. I hate having my multi charger in carry on luggage but phone charging cables the checked baggage.

I will be watching the development of this promising app.And recommending it to others.

**Comment by nbossard** [comment]
Since v0.10 we now have a basic support of categories in lists.
